[package]
name = "curly-gui"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
eframe = { version = "0.36.1", default-features = false, features = ["default_fonts", "glow", "wayland", "x11"] }
egui = "0.36.1"
curly-core = { path = "../curly-core" }
reqwest = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
